### ISSUE TITLE
exec ./wait-for-postgres.sh: no such file or directory

### ISSUE THREAD

**Issue by NGoren613** [netreconlab/parse-hipaa#110]
I cloned the repo. Didn't change anything. Tried basic docker compose up for initial testing.
db and dashboard seem to run fine.
parse-hipaa gives this message and shuts down:
```
parse-hipaa-parse-1      | exec ./wait-for-postgres.sh: no such file or directory
parse-hipaa-parse-1 exited with code 1
```

**Comment by cbaker6** [comment]
I suspect there is something you cloned incorrectly as I just tried the instructions here: https://github.com/netreconlab/parse-hipaa?tab=readme-ov-file#postgres and don't see the warning you mentioned. Note that the script is in the docker file here: https://github.com/netreconlab/parse-hipaa/blob/main/scripts/wait-for-postgres.sh.

In terminal, navigate to the the parse-hipaa directory and type: `docker compose up -d`

**Comment by cbaker6** [comment]
It's possible you have old versions of the images (if you used parse-hipaa years ago on your computer) you can check for this by typing the following in your terminal: `docker images`. You should see something like:

```bash
(base) coreybaker@usc-guestwireless-upc-newsc20622 parse-hipaa % docker images
REPOSITORY                                                                                             TAG       IMAGE ID       CREATED        SIZE
netreconlab/hipaa-postgres                                                                             latest    a8feb0054add   4 days ago     579MB
netreconlab/hipaa-mongo                                                                                latest    bc32193b960e   2 weeks ago    897MB
netreconlab/parse-hipaa-dashboard                                                                      latest    a7e5a0921878   2 weeks ago    267MB
netreconlab/parse-hipaa                                                                                latest    c8c2e982a94e   2 weeks ago    381MB
```

**Comment by NGoren613** [comment]
That could be it. Tested it on my laptop this morning and it seems to run fine. I'll have to look for those on my desktop this weekend. I did test it with mongo on my desktop and it seemed to work okay. Thanks
