### ISSUE TITLE
PostgreSQL does not start

### ISSUE THREAD

**Issue by advatar** [netreconlab/parse-hipaa#14]
Revisiting and now when I tried launch the dockers I get:

db_1         | 
db_1         | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1         | 
db_1         | 2021-02-01 17:35:03.624 UTC [1] FATAL:  database files are incompatible with server
db_1         | 2021-02-01 17:35:03.624 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 12, which is not compatible with this version 13.1 (Debian 13.1-1.pgdg100+1).

And then 

parse_1      | psql: error: could not translate host name "db" to address: Name does not resolve
parse_1      | Postgres is unavailable on db - parse-server is sleeping

**Comment by cbaker6** [comment]
You need to use `docker-compose down", then `docker-compose up`.

It looks like you had an older version of the branch `Postgres 12`, and now have the newer version `Postgres 13`

**Comment by advatar** [comment]
Thanks, I scratched all containers and now it works again.
