### ISSUE TITLE
parse-hipaa-parse-1 exited with code 1

### ISSUE THREAD

**Issue by kiwifruituk** [netreconlab/parse-hipaa#93]
I'm running `docker-compose up` in the forked repo on `snapcat` branch, but am getting the following error. Any help would be grand!

parse-hipaa-parse-1      | Postgres is up - executing command: node index.js
parse-hipaa-parse-1      | warn: DeprecationWarning: The Parse Server option 'encodeParseObjectInCloudFunction' default will change to 'true' in a future version.
parse-hipaa-parse-1      | node:internal/process/promises:288
parse-hipaa-parse-1      |             triggerUncaughtException(err, true /* fromPromise */);
parse-hipaa-parse-1      |             ^
parse-hipaa-parse-1      |
parse-hipaa-parse-1      | [UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "fileUpload.fileExtensions must be an array.".] {
parse-hipaa-parse-1      |   code: 'ERR_UNHANDLED_REJECTION'
parse-hipaa-parse-1      | }
parse-hipaa-parse-1      |
parse-hipaa-parse-1      | Node.js v18.17.1
parse-hipaa-parse-1 exited with code 1

**Comment by kiwifruituk** [comment]
It worked when I downloaded the zip file as opposed to cloning the repo

**Comment by kiwifruituk** [comment]
False positive - it works on the `main` branch, not the `SnapCat` branch - same error

**Comment by cbaker6** [comment]
Thanks for reporting, the SnapCat branch has been fixed here: https://github.com/netreconlab/parse-hipaa/commit/3efc56969a7b3afbbbf8601e2e3fe60b20063237
